parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    SymfonyCon\Mastermind\UseCase\:
        resource: '../../../../UseCase/*'

    SymfonyCon\Mastermind\Adapters\Web\Controller\:
        resource: '../../../../Adapters/Web/Controller'
        tags: ['controller.service_arguments']

    SymfonyCon\Mastermind\UseCase\StartGameUseCase:
        arguments:
            $numberOfAttempts: 12

    SymfonyCon\Mastermind\Game\DecodingBoards: '@SymfonyCon\Mastermind\Adapters\Database\DoctrineDecodingBoards'
    SymfonyCon\Mastermind\Adapters\Session\SessionDecodingBoards: ~
    SymfonyCon\Mastermind\Adapters\Database\DoctrineDecodingBoards: ~

    SymfonyCon\Mastermind\Game\CodeMaker: '@SymfonyCon\Mastermind\Game\RandomCodeMaker'
    SymfonyCon\Mastermind\Game\RandomCodeMaker: ~
